CREATE TABLE MOA_BIBLE_TODAY_WORDS
(
	SEQ_NO						BIGINT auto_increment NOT NULL KEY,
	SORT_SEQ_NO			INT(8) NOT NULL,
	CHAPTER    				INT(8) NOT NULL,
	VERSE      					INT(8) NOT NULL,
	KEY bible_today_key1(SORT_SEQ_NO, CHAPTER, VERSE)
);
ALTER TABLE MOA_BIBLE_TODAY_WORDS AUTO_INCREMENT = 1;