CREATE TABLE MOA_BIBLE
(
	SEQ_NO						BIGINT auto_increment NOT NULL KEY,
	EVER_SEQ_NO			INT(8),
	TRANSLATE_SEQ_NO	INT(8) NOT NULL,
	SORT_SEQ_NO			INT(8) NOT NULL,
	TESTAMENT					VARCHAR(10) NOT NULL,
	CHAPTER    				INT(8) NOT NULL,
	VERSE      					INT(8) NOT NULL,
	WORDS      				VARCHAR(4000)
);
ALTER TABLE MOA_BIBLE AUTO_INCREMENT = 1;

CREATE TABLE MOA_BIBLE_BY_TRANSLATE
(
	SEQ_NO						INT(8) auto_increment NOT NULL KEY,
	CODE							VARCHAR(10),
	NAME							VARCHAR(30),
	LANGUAGE					VARCHAR(10)
);
ALTER TABLE MOA_BIBLE_BY_TRANSLATE AUTO_INCREMENT = 1;

CREATE TABLE MOA_BIBLE_BY_SORT
(
	SEQ_NO						INT(8) auto_increment NOT NULL KEY,
	EVER_SEQ_NO			INT(8) NOT NULL,
	CHAPTER_NUM			INT(8),
	ENUM_NAME				VARCHAR(10),
	NAME_SHORT				VARCHAR(10),
	NAME							VARCHAR(50),
	LANGUAGE					VARCHAR(10),
	TESTAMENT					VARCHAR(10)
);
ALTER TABLE MOA_BIBLE_BY_SORT AUTO_INCREMENT = 1;

CREATE TABLE MOA_BIBLE_BY_SORT_CHAPTER
(
	SEQ_NO								INT(8) auto_increment NOT NULL KEY,
	BIBLE_BY_SORT_SEQ_NO		INT(8),
	CHAPTER							INT(8),
	VERSE_NUM						INT(8)
);
ALTER TABLE MOA_BIBLE_BY_SORT_CHAPTER AUTO_INCREMENT = 1;