CREATE TABLE MOA_QUIZSET
(
	SEQ_NO				BIGINT auto_increment NOT NULL KEY,
	TITLE				VARCHAR(300),
	DESCRIPTION				TEXT,
	QUIZ_SEQ_NO			BIGINT,
	SORT_ORDER			INT,
	READ_COUNT			BIGINT,
	RESOLVE_COUNT		BIGINT,
	CREATE_USER			VARCHAR(20),
	CREATE_DATE			DATE,
	UPDATE_USER			VARCHAR(20),
	UPDATE_DATE			DATE
);
ALTER TABLE MOA_QUIZSET AUTO_INCREMENT = 1;

CREATE TABLE MOA_QUIZ
(
	SEQ_NO				BIGINT auto_increment NOT NULL KEY,
	TITLE				VARCHAR(300) NOT NULL,
	TYPE				VARCHAR(20) NOT NULL,
	ANSWER				VARCHAR(300) NOT NULL,
	HINT				VARCHAR(300),
	DESCRIPTION				TEXT,
	LINK_URL   			VARCHAR(300),
	IMAGE_URL      		VARCHAR(300),
	RESOLVE_COUNT		BIGINT,
	CORRECT_COUNT		BIGINT,
	CREATE_USER			VARCHAR(20),
	CREATE_DATE			DATE,
	UPDATE_USER			VARCHAR(20),
	UPDATE_DATE			DATE
);
ALTER TABLE MOA_QUIZ AUTO_INCREMENT = 1;

CREATE TABLE MOA_QUIZ_QUESTION
(
	SEQ_NO				BIGINT auto_increment NOT NULL KEY,
	QUIZ_SEQ_NO			BIGINT NOT NULL,
	QUESTION			VARCHAR(300),
	SORT_ORDER			INT,
	CHOICE_COUNT		BIGINT
);
ALTER TABLE MOA_QUIZ_QUESTION AUTO_INCREMENT = 1;

CREATE TABLE MOA_QUIZ_HISTORY
(
	SEQ_NO				BIGINT auto_increment NOT NULL KEY,
	USER_ID				VARCHAR(20),
	QUIZ_SEQ_NO			BIGINT,
	CHOICE_SEQ_NO		BIGINT,
	IS_CORRECT			CHAR(1),
	CREATE_DATE			DATE
);
ALTER TABLE MOA_QUIZ_HISTORY AUTO_INCREMENT = 1;